### PR TITLE
added support for password hash check

### PR DESCRIPTION
**Pull request by sdushantha**
The password for all users is `password`

The password hashing method that will be used is Bcrypt as it's widely used for hashing passwords. Popular apps such as Snapchat and Instagram use Bcrypt.

Bcrypt is much slower than hashing algorithms such as SHA1 which is quite beniticial for password hashing as it makes brute forcing the password more difficult. In addition, Bcrypt prepends a random 16 byte salt to the plaint text password.

More on Bcrypt: https://nordvpn.com/blog/what-is-bcrypt/

https://github.com/sdushantha/bookingsystem/assets/27065646/1cd7387b-b73a-4e40-b387-9831e9a8c938

### CODE REVIEW

**Comment by sdushantha** [comment]
Side for å lage ny bruker funker nå :ok_hand: 

https://github.com/sdushantha/bookingsystem/assets/27065646/767e7bda-286e-45c3-87e4-331f51f95253

**Comment by sdushantha** [comment]
Kom på nå at vi trenge muligens en annen side for registrering av supervisor og en login for admin slik at admin kan utdele rettigheter og sånt

**Comment by torkelhi** [comment]
kan du utdype - "En custom "echo" kan trenges som automatisk fjerner HTML og PHP kode"

**Review by torkelhi — APPROVED** [review]
Vi trenger validering på riktig formatering, og tomme input felt.
Ellers ser det bra ut.

Approver denne, men lager en issue eller en oppgave på den.

**Pull request merged**
